/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repasoo;

import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author WIND 10
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Ejercicio 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ejercicio 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ejercicio 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Ejercicio 4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Ejercicio 5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Ejercicio 6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Ejercicio 7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Ejercicio 8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Ejercicio 10");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel2.setText("REPASO");

        jButton10.setText("Ejercicio 9");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton4)
                        .addComponent(jButton7))
                    .addComponent(jButton1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton8)
                            .addComponent(jButton2)
                            .addComponent(jButton9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(169, 169, 169))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        // Ejercicio 1
        int num1, num2, sum,res,mod1,mod2;
        Scanner scanner = new Scanner(System.in);
        System.out.println("***SUMA, RESTA Y RESIDUO***");
        System.out.println("Ingrese el primer numero");
        num1 = scanner.nextInt();
        System.out.println("Ingrese el segundo numero");
        num2 = scanner.nextInt();
        
        sum = num1+num2;
        res = num1-num2;
        mod1 = num1%2;
        mod2 = num2%2;
        
        System.out.println("La suma de los dos numeros es "+sum);
        System.out.println("La resta de los dos numeros es "+res);
        System.out.println("El modulo del primer numero es "+mod1);
        System.out.println("El modulo del segundo numero es "+mod2);
        //fin del codigo
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        //Ejercicio 2
        /*String opc1 = "Leon",opc2 = "Rosa",opc3 = "Hongo" ,opc4 = "Alga",opc5 = "Pinguino", opc;
        Scanner scanner = new Scanner(System.in);
        System.out.println("Escriba un ser vivo");
        opc= scanner.next();
        
        if(opc==opc1){
            System.out.println("El ser vivo pertenece al reino animal");
          if(opc==opc5){
               System.out.println("El ser vivo pertenece al reino animal"); 
            }
        }*/
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //Ejercicio 3
        JOptionPane.showMessageDialog(null, "**NOTAS MUSICALES**");
        String not=JOptionPane.showInputDialog("Escriba un numero del 1 al 7");
        int nota = Integer.parseInt(not);
        
        switch(nota){
            case 1:
                JOptionPane.showMessageDialog(null, "La nota correspondiente es DO");
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "La nota correspondiente es RE");
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "La nota correspondiente es MI");
                break;
            case 4:
                JOptionPane.showMessageDialog(null, "La nota correspondiente es FA");
                break;
            case 5:
                JOptionPane.showMessageDialog(null, "La nota correspondiente es SOL");
                break;
            case 6:
                JOptionPane.showMessageDialog(null, "La nota correspondiente es LA");
                break;
            case 7:
                JOptionPane.showMessageDialog(null, "La nota correspondiente es SI");
                break;
            default:
                JOptionPane.showMessageDialog(null, "El numero no corresponde a nunguna nota musical\n"+"!Vuelva a intentar¡");
                break;
    
    }
        //fin del codigo
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Ejercicio 4
        JOptionPane.showMessageDialog(null, "**SECUENCIA**");
        String numero=JOptionPane.showInputDialog("Escriba un numero");
        int num = Integer.parseInt(numero);
        
        for (int i = 0; i <= num; i++) {
            JOptionPane.showMessageDialog(null,i);
        }
        //fin del codigo
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //Ejercicio 5
        JOptionPane.showMessageDialog(null, "**SECUENCIA N°2**");
        String numero=JOptionPane.showInputDialog("Escriba un numero");
        int num = Integer.parseInt(numero);
        
        for (int i = 0; i <= num; i = i+3) {
            JOptionPane.showMessageDialog(null,i);
        }
        //fin del codigo
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //Ejercicio 6
        JOptionPane.showMessageDialog(null, "**NUMEROS PARES**");
        String numero=JOptionPane.showInputDialog("Escriba un numero");
        int num = Integer.parseInt(numero);
        
        if(num%2==0){
            JOptionPane.showMessageDialog(null,"El numero ingresado es par");
        }
        else{
            JOptionPane.showMessageDialog(null,"El numero ingresado es impar");
        }
        //Fin del codigo
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //Ejercicio 7
        JOptionPane.showMessageDialog(null, "**SERIE FINONACCI**");
        String numero=JOptionPane.showInputDialog("Cuantos numeros desea generar");
        int num = Integer.parseInt(numero);
        
        int f=0,t1=1,t2;
        
        for(int i = 1;i<=num;i++){
            
            t2 = f;
            f = t1+f;
            t1 = t2;
            //System.out.println(""+t1);
            JOptionPane.showMessageDialog(null, t1);
        }
        //Fin del codigo
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //Ejercicio 9
        Hipotenusa hipo = new Hipotenusa();
        hipo.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //Ejercicio 8
        
        int contra=1583,pasw = 0;
        JOptionPane.showMessageDialog(null,"Adivina la contraseña ");
        JOptionPane.showMessageDialog(null, "PISTA");
        JOptionPane.showMessageDialog(null, "Es un numero de 4 digitos");
        
        for (int i = 1; i <= 3; i++) {
            String pas=JOptionPane.showInputDialog("Intento: "+i);
            pasw = Integer.parseInt(pas);
            
            if(pasw==contra){
                JOptionPane.showMessageDialog(null,"Acceso permitido");
                break;
            }
            else{
                JOptionPane.showMessageDialog(null,"Acceso denegado ");
            }
        }
        
        if(pasw!=contra){
            JOptionPane.showMessageDialog(null,"Contrañesa bloqueada ");
        }
        //Fin del codigo
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // Ejercicio 9
        // Numero factorial y IMC
        int ter,fac,num;
        double alt,pes,imc;
        
        JOptionPane.showMessageDialog(null, "**BIENVENIDO**");
        String termina = JOptionPane.showInputDialog("Que operacion desea realizar \n"+"1.Factorial\n"+"2.IMC\n"+"3.Salir");
        ter = Integer.parseInt(termina);
       
            
            switch (ter){
                case 1:
                        String factorial=JOptionPane.showInputDialog("Ingrese el numero");
                        num = Integer.parseInt(factorial);
                        //ejemplo: 4 = 4*3*2*1 = 24
                        fac=1;
        
                        for(int i=1;i<=num;i++){
                        fac=fac*i;
                         }
                        JOptionPane.showMessageDialog(null, "El numero factorial de "+num+" es "+fac);
                        break;
                case 2:
                    
                        String altura=JOptionPane.showInputDialog("Ingrese la altura  en metros");
                        alt = Double.parseDouble(altura);
                        String peso=JOptionPane.showInputDialog("Ingrese el peso");
                        pes = Double.parseDouble(peso);
                        
                        imc = pes/(Math.pow(alt, 2));
                                                                        
                        if(imc<=18.5){
                            JOptionPane.showMessageDialog(null,"Su peso en inferior al normal ");   
                        }
                        if(imc>=18.6&&imc<=24.9){
                            JOptionPane.showMessageDialog(null,"Su peso es normal ");                             
                        }
                        if(imc>=25&&imc<=29.9){
                           JOptionPane.showMessageDialog(null,"Su peso en superior al normal ");                            
                        }
                        if(imc>=30){
                            JOptionPane.showMessageDialog(null,"Usted tiene sobrepeso ");                             
                        }
                        break;
                case 3:   
                        break;
                default: 
                    JOptionPane.showMessageDialog(null,"Esa no es una opcion valida"); 
                        
            
            }
            //Fin del codigo
        
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
